<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class ApprovedAndPendingUsersSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('vendors')->truncate();
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $users = [
            // Admin user
            [
                'name' => 'System Admin',
                'email' => 'admin@autochain.com',
                'password' => Hash::make('adminpassword'),
                'role' => 'admin',
                'status' => 'approved',
                'company' => 'AutoChain HQ',
                'phone' => '+1-555-0000',
                'address' => '1 Admin Plaza, HQ City',
                'profile_photo' => 'images/profile/admin.jpeg',
                'supporting_documents' => json_encode([]),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Vendors (20 approved, realistic details)
            [
                'name' => 'Ava Carter',
                'email' => 'ava.carter@vendortech.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorTech Solutions',
                'phone' => '+1-555-1101',
                'address' => '101 Vendor Lane, New York, NY',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['ava_carter_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Benjamin Lee',
                'email' => 'benjamin.lee@autovend.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'AutoVend Inc.',
                'phone' => '+1-555-1102',
                'address' => '202 Market St, Los Angeles, CA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['benjamin_lee_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chloe Kim',
                'email' => 'chloe.kim@partsplus.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'PartsPlus',
                'phone' => '+1-555-1103',
                'address' => '303 Commerce Ave, Chicago, IL',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['chloe_kim_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Patel',
                'email' => 'david.patel@vendormax.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorMax',
                'phone' => '+1-555-1104',
                'address' => '404 Vendor Blvd, Dallas, TX',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['david_patel_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ella Zhang',
                'email' => 'ella.zhang@autopartspro.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'AutoParts Pro',
                'phone' => '+1-555-1105',
                'address' => '505 Parts Ave, San Francisco, CA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['ella_zhang_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Frank Müller',
                'email' => 'frank.muller@vendorexpress.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorExpress',
                'phone' => '+1-555-1106',
                'address' => '606 Express Rd, Miami, FL',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['frank_muller_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grace Park',
                'email' => 'grace.park@vendornet.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorNet',
                'phone' => '+1-555-1107',
                'address' => '707 Network St, Seattle, WA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['grace_park_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Henry Kim',
                'email' => 'henry.kim@vendorglobal.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorGlobal',
                'phone' => '+1-555-1108',
                'address' => '808 Global Ave, Boston, MA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['henry_kim_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabella Rossi',
                'email' => 'isabella.rossi@vendormarket.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorMarket',
                'phone' => '+1-555-1109',
                'address' => '909 Market St, Chicago, IL',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['isabella_rossi_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jack Wilson',
                'email' => 'jack.wilson@vendordirect.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorDirect',
                'phone' => '+1-555-1110',
                'address' => '1010 Direct Dr, Austin, TX',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['jack_wilson_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Katherine Lee',
                'email' => 'katherine.lee@vendornow.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorNow',
                'phone' => '+1-555-1111',
                'address' => '1111 Now St, Denver, CO',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['katherine_lee_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liam Brown',
                'email' => 'liam.brown@vendorteam.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorTeam',
                'phone' => '+1-555-1112',
                'address' => '1212 Team Ave, San Diego, CA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['liam_brown_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mia Garcia',
                'email' => 'mia.garcia@vendornetwork.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorNetwork',
                'phone' => '+1-555-1113',
                'address' => '1313 Network Blvd, Orlando, FL',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['mia_garcia_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Noah Smith',
                'email' => 'noah.smith@vendorgroup.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorGroup',
                'phone' => '+1-555-1114',
                'address' => '1414 Group St, Atlanta, GA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['noah_smith_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olivia Davis',
                'email' => 'olivia.davis@vendormarket.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorMarket',
                'phone' => '+1-555-1115',
                'address' => '1515 Market Ave, Charlotte, NC',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['olivia_davis_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paul Walker',
                'email' => 'paul.walker@vendorlink.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorLink',
                'phone' => '+1-555-1116',
                'address' => '1616 Link St, Portland, OR',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['paul_walker_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quinn Harris',
                'email' => 'quinn.harris@vendornet.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorNet',
                'phone' => '+1-555-1117',
                'address' => '1717 Net Ave, Minneapolis, MN',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['quinn_harris_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ryan Clark',
                'email' => 'ryan.clark@vendorconnect.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorConnect',
                'phone' => '+1-555-1118',
                'address' => '1818 Connect Blvd, Salt Lake City, UT',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['ryan_clark_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophia Martinez',
                'email' => 'sophia.martinez@vendorplus.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorPlus',
                'phone' => '+1-555-1119',
                'address' => '1919 Plus St, San Antonio, TX',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['sophia_martinez_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tyler Nguyen',
                'email' => 'tyler.nguyen@vendortech.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'VendorTech',
                'phone' => '+1-555-1120',
                'address' => '2020 Tech Ave, San Jose, CA',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['tyler_nguyen_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Manufacturers (20 approved, realistic details)
            [
                'name' => 'Daniel Smith',
                'email' => 'daniel.smith@manufactory.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Manufactory Ltd.',
                'phone' => '+1-555-1201',
                'address' => '401 Factory Rd, Detroit, MI',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['daniel_smith_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ella Brown',
                'email' => 'ella.brown@automan.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoMan Corp.',
                'phone' => '+1-555-1202',
                'address' => '502 Assembly St, Houston, TX',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['ella_brown_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Frank Wilson',
                'email' => 'frank.wilson@buildit.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'BuildIt Manufacturing',
                'phone' => '+1-555-1203',
                'address' => '603 Industrial Ave, Seattle, WA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['frank_wilson_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grace Lee',
                'email' => 'grace.lee@manuworks.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuWorks',
                'phone' => '+1-555-1204',
                'address' => '704 Works Blvd, San Jose, CA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['grace_lee_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Henry Adams',
                'email' => 'henry.adams@autoforge.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoForge',
                'phone' => '+1-555-1205',
                'address' => '805 Forge St, Boston, MA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['henry_adams_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabella Turner',
                'email' => 'isabella.turner@manuplus.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuPlus',
                'phone' => '+1-555-1206',
                'address' => '906 Plus Ave, Austin, TX',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['isabella_turner_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jack Evans',
                'email' => 'jack.evans@manuprime.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuPrime',
                'phone' => '+1-555-1207',
                'address' => '1007 Prime Rd, Denver, CO',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['jack_evans_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Katherine White',
                'email' => 'katherine.white@automanufacture.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoManufacture',
                'phone' => '+1-555-1208',
                'address' => '1108 Manufacture St, Charlotte, NC',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['katherine_white_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liam Harris',
                'email' => 'liam.harris@manuengine.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuEngine',
                'phone' => '+1-555-1209',
                'address' => '1209 Engine Ave, Portland, OR',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['liam_harris_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mia Clark',
                'email' => 'mia.clark@manuworks.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuWorks',
                'phone' => '+1-555-1210',
                'address' => '1210 Works Blvd, San Diego, CA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['mia_clark_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Noah Martinez',
                'email' => 'noah.martinez@manuplus.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuPlus',
                'phone' => '+1-555-1211',
                'address' => '1211 Plus Ave, Orlando, FL',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['noah_martinez_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olivia Davis',
                'email' => 'olivia.davis@manufactory.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Manufactory Ltd.',
                'phone' => '+1-555-1212',
                'address' => '1212 Factory Rd, Atlanta, GA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['olivia_davis_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paul Walker',
                'email' => 'paul.walker@automan.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoMan Corp.',
                'phone' => '+1-555-1213',
                'address' => '1213 Assembly St, Salt Lake City, UT',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['paul_walker_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quinn Harris',
                'email' => 'quinn.harris@manuprime.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuPrime',
                'phone' => '+1-555-1214',
                'address' => '1214 Prime Rd, Minneapolis, MN',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['quinn_harris_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ryan Clark',
                'email' => 'ryan.clark@automanufacture.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoManufacture',
                'phone' => '+1-555-1215',
                'address' => '1215 Manufacture St, Charlotte, NC',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['ryan_clark_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophia Martinez',
                'email' => 'sophia.martinez@manuengine.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuEngine',
                'phone' => '+1-555-1216',
                'address' => '1216 Engine Ave, San Antonio, TX',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['sophia_martinez_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tyler Nguyen',
                'email' => 'tyler.nguyen@manuplus.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuPlus',
                'phone' => '+1-555-1217',
                'address' => '1217 Plus Ave, San Jose, CA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['tyler_nguyen_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uma Patel',
                'email' => 'uma.patel@manuworks.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'ManuWorks',
                'phone' => '+1-555-1218',
                'address' => '1218 Works Blvd, Miami, FL',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['uma_patel_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Victor Kim',
                'email' => 'victor.kim@manufactory.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Manufactory Ltd.',
                'phone' => '+1-555-1219',
                'address' => '1219 Factory Rd, Boston, MA',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['victor_kim_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Willow Brown',
                'email' => 'willow.brown@automan.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoMan Corp.',
                'phone' => '+1-555-1220',
                'address' => '1220 Assembly St, Houston, TX',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['willow_brown_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Suppliers (20 approved, realistic details)
            [
                'name' => 'Alice Morgan',
                'email' => 'alice.morgan@supplyco.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SupplyCo',
                'phone' => '+1-555-1301',
                'address' => '301 Supply Blvd, Dallas, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['alice_morgan_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brian Lee',
                'email' => 'brian.lee@rawsource.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'RawSource',
                'phone' => '+1-555-1302',
                'address' => '302 Source St, Houston, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['brian_lee_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carla Diaz',
                'email' => 'carla.diaz@partsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartSupply',
                'phone' => '+1-555-1303',
                'address' => '303 Parts Ave, Miami, FL',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['carla_diaz_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Derek Kim',
                'email' => 'derek.kim@supersupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SuperSupply',
                'phone' => '+1-555-1304',
                'address' => '304 Super St, Boston, MA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['derek_kim_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eva Turner',
                'email' => 'eva.turner@globalsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'GlobalSupply',
                'phone' => '+1-555-1305',
                'address' => '305 Global Ave, San Francisco, CA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['eva_turner_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Felix Brown',
                'email' => 'felix.brown@sourceplus.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SourcePlus',
                'phone' => '+1-555-1306',
                'address' => '306 Plus St, Austin, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['felix_brown_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gina Evans',
                'email' => 'gina.evans@supersource.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SuperSource',
                'phone' => '+1-555-1307',
                'address' => '307 Source Blvd, Seattle, WA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['gina_evans_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Henry Adams',
                'email' => 'henry.adams@partsco.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartsCo',
                'phone' => '+1-555-1308',
                'address' => '308 Parts Blvd, Orlando, FL',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['henry_adams_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ivy Turner',
                'email' => 'ivy.turner@globalsource.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'GlobalSource',
                'phone' => '+1-555-1309',
                'address' => '309 Global St, Atlanta, GA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['ivy_turner_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jack Wilson',
                'email' => 'jack.wilson@partsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartSupply',
                'phone' => '+1-555-1310',
                'address' => '310 Supply Ave, Charlotte, NC',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['jack_wilson_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Katherine Lee',
                'email' => 'katherine.lee@sourceco.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SourceCo',
                'phone' => '+1-555-1311',
                'address' => '311 Source Blvd, San Diego, CA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['katherine_lee_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liam Brown',
                'email' => 'liam.brown@partsplus.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartsPlus',
                'phone' => '+1-555-1312',
                'address' => '312 Plus Ave, San Antonio, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['liam_brown_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mia Garcia',
                'email' => 'mia.garcia@globalsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'GlobalSupply',
                'phone' => '+1-555-1313',
                'address' => '313 Global Blvd, Portland, OR',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['mia_garcia_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Noah Smith',
                'email' => 'noah.smith@sourceplus.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SourcePlus',
                'phone' => '+1-555-1314',
                'address' => '314 Plus St, Orlando, FL',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['noah_smith_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olivia Davis',
                'email' => 'olivia.davis@partsco.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartsCo',
                'phone' => '+1-555-1315',
                'address' => '315 Parts Blvd, Boston, MA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['olivia_davis_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paul Walker',
                'email' => 'paul.walker@rawsource.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'RawSource',
                'phone' => '+1-555-1316',
                'address' => '316 Source St, Houston, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['paul_walker_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quinn Harris',
                'email' => 'quinn.harris@partsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartSupply',
                'phone' => '+1-555-1317',
                'address' => '317 Supply Ave, Charlotte, NC',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['quinn_harris_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ryan Clark',
                'email' => 'ryan.clark@sourceco.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'SourceCo',
                'phone' => '+1-555-1318',
                'address' => '318 Source Blvd, San Diego, CA',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['ryan_clark_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophia Martinez',
                'email' => 'sophia.martinez@partsplus.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'PartsPlus',
                'phone' => '+1-555-1319',
                'address' => '319 Plus Ave, San Antonio, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['sophia_martinez_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tyler Nguyen',
                'email' => 'tyler.nguyen@globalsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'GlobalSupply',
                'phone' => '+1-555-1320',
                'address' => '320 Global Blvd, Portland, OR',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['tyler_nguyen_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Retailers (20 approved, realistic details)
            [
                'name' => 'Olivia Turner',
                'email' => 'olivia.turner@retailmart.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailMart',
                'phone' => '+1-555-1401',
                'address' => '201 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['olivia_turner_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Ethan Brooks',
                'email' => 'ethan.brooks@shopwise.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'ShopWise',
                'phone' => '+1-555-1402',
                'address' => '202 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['ethan_brooks_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Sophia Bennett',
                'email' => 'sophia.bennett@urbanstore.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'UrbanStore',
                'phone' => '+1-555-1403',
                'address' => '203 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['sophia_bennett_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Liam Murphy',
                'email' => 'liam.murphy@quickmart.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'QuickMart',
                'phone' => '+1-555-1404',
                'address' => '204 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['liam_murphy_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Mia Collins',
                'email' => 'mia.collins@superstore.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'SuperStore',
                'phone' => '+1-555-1405',
                'address' => '205 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['mia_collins_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Noah Reed',
                'email' => 'noah.reed@marketplace.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'MarketPlace',
                'phone' => '+1-555-1406',
                'address' => '206 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['noah_reed_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Charlotte Hayes',
                'email' => 'charlotte.hayes@retailplus.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailPlus',
                'phone' => '+1-555-1407',
                'address' => '207 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['charlotte_hayes_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Lucas Perry',
                'email' => 'lucas.perry@shopcity.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'ShopCity',
                'phone' => '+1-555-1408',
                'address' => '208 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['lucas_perry_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Amelia Foster',
                'email' => 'amelia.foster@retailzone.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailZone',
                'phone' => '+1-555-1409',
                'address' => '209 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['amelia_foster_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Mason Gray',
                'email' => 'mason.gray@shopmart.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'ShopMart',
                'phone' => '+1-555-1410',
                'address' => '210 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['mason_gray_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Ella Price',
                'email' => 'ella.price@retailworld.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailWorld',
                'phone' => '+1-555-1411',
                'address' => '211 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['ella_price_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Logan Bell',
                'email' => 'logan.bell@shopwise.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'ShopWise',
                'phone' => '+1-555-1412',
                'address' => '212 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['logan_bell_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Harper Evans',
                'email' => 'harper.evans@retailmart.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailMart',
                'phone' => '+1-555-1413',
                'address' => '213 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['harper_evans_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Benjamin Scott',
                'email' => 'benjamin.scott@urbanstore.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'UrbanStore',
                'phone' => '+1-555-1414',
                'address' => '214 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['benjamin_scott_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Emily Adams',
                'email' => 'emily.adams@quickmart.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'QuickMart',
                'phone' => '+1-555-1415',
                'address' => '215 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['emily_adams_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Jack Morris',
                'email' => 'jack.morris@superstore.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'SuperStore',
                'phone' => '+1-555-1416',
                'address' => '216 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['jack_morris_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Grace Walker',
                'email' => 'grace.walker@marketplace.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'MarketPlace',
                'phone' => '+1-555-1417',
                'address' => '217 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['grace_walker_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Henry King',
                'email' => 'henry.king@retailplus.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailPlus',
                'phone' => '+1-555-1418',
                'address' => '218 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['henry_king_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'Zoe Cooper',
                'email' => 'zoe.cooper@shopcity.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'ShopCity',
                'phone' => '+1-555-1419',
                'address' => '219 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['zoe_cooper_doc1.pdf']),
                'auto_visit_scheduled' => null,
            ],
            [
                'name' => 'William Hughes',
                'email' => 'william.hughes@retailzone.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'RetailZone',
                'phone' => '+1-555-1420',
                'address' => '220 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['william_hughes_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            // Analysts (20 approved, realistic details)
            [
                'name' => 'Samuel Carter',
                'email' => 'samuel.carter@analytica.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Analytica Insights',
                'phone' => '+1-555-1501',
                'address' => '101 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['samuel_carter_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Victoria Lee',
                'email' => 'victoria.lee@datawise.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'DataWise Analytics',
                'phone' => '+1-555-1502',
                'address' => '102 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['victoria_lee_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Matthew Kim',
                'email' => 'matthew.kim@insightpro.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'InsightPro',
                'phone' => '+1-555-1503',
                'address' => '103 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['matthew_kim_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Chloe Adams',
                'email' => 'chloe.adams@trendlytics.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'TrendLytics',
                'phone' => '+1-555-1504',
                'address' => '104 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['chloe_adams_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Ryan Foster',
                'email' => 'ryan.foster@marketintel.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'MarketIntel',
                'phone' => '+1-555-1505',
                'address' => '105 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['ryan_foster_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Ella Brooks',
                'email' => 'ella.brooks@analytix.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Analytix Group',
                'phone' => '+1-555-1506',
                'address' => '106 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['ella_brooks_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'David Green',
                'email' => 'david.green@insightful.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Insightful Analytics',
                'phone' => '+1-555-1507',
                'address' => '107 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['david_green_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Sofia Turner',
                'email' => 'sofia.turner@datanova.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'DataNova',
                'phone' => '+1-555-1508',
                'address' => '108 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['sofia_turner_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Jackson Lee',
                'email' => 'jackson.lee@marketmetrics.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'MarketMetrics',
                'phone' => '+1-555-1509',
                'address' => '109 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['jackson_lee_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Grace Evans',
                'email' => 'grace.evans@trendwise.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'TrendWise',
                'phone' => '+1-555-1510',
                'address' => '110 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['grace_evans_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Benjamin Scott',
                'email' => 'benjamin.scott@insightedge.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'InsightEdge',
                'phone' => '+1-555-1511',
                'address' => '111 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['benjamin_scott_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Lily Parker',
                'email' => 'lily.parker@datanalytics.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'DataNaltyics',
                'phone' => '+1-555-1512',
                'address' => '112 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['lily_parker_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Mason Rivera',
                'email' => 'mason.rivera@marketinsight.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'MarketInsight',
                'phone' => '+1-555-1513',
                'address' => '113 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['mason_rivera_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Avery Morgan',
                'email' => 'avery.morgan@analytica.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Analytica Insights',
                'phone' => '+1-555-1514',
                'address' => '114 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['avery_morgan_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Logan Bailey',
                'email' => 'logan.bailey@datawise.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'DataWise Analytics',
                'phone' => '+1-555-1515',
                'address' => '115 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['logan_bailey_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Scarlett Reed',
                'email' => 'scarlett.reed@insightpro.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'InsightPro',
                'phone' => '+1-555-1516',
                'address' => '116 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['scarlett_reed_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Elijah Cooper',
                'email' => 'elijah.cooper@trendlytics.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'TrendLytics',
                'phone' => '+1-555-1517',
                'address' => '117 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['elijah_cooper_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Penelope Ross',
                'email' => 'penelope.ross@marketintel.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'MarketIntel',
                'phone' => '+1-555-1518',
                'address' => '118 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['penelope_ross_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Carter James',
                'email' => 'carter.james@analytix.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Analytix Group',
                'phone' => '+1-555-1519',
                'address' => '119 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['carter_james_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Layla Bennett',
                'email' => 'layla.bennett@insightful.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Insightful Analytics',
                'phone' => '+1-555-1520',
                'address' => '120 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['layla_bennett_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],

            //Pending users 
            [
                'name' => 'Natalie Simmons',
                'email' => 'natalie.simmons@vendortech.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'VendorTech Solutions',
                'phone' => '+1-555-1601',
                'address' => '301 Vendor Lane, New York, NY',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['natalie_simmons_doc1.pdf']),
                'auto_visit_scheduled' => false
            ],
            [
                'name' => 'Derek Foster',
                'email' => 'derek.foster@vendormax.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'VendorMax',
                'phone' => '+1-555-1602',
                'address' => '302 Vendor Lane, New York, NY',
                'profile_photo' => 'images/profile/vendor.jpeg',
                'supporting_documents' => json_encode(['derek_foster_doc1.pdf']),
                'auto_visit_scheduled' => false
            ],
            [
                'name' => 'Isabella Grant',
                'email' => 'isabella.grant@manufactory.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Manufactory Ltd.',
                'phone' => '+1-555-1701',
                'address' => '501 Factory Rd, Detroit, MI',
                'profile_photo' => 'images/profile/manufacturer.jpeg',
                'supporting_documents' => json_encode(['isabella_grant_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Owen Parker',
                'email' => 'owen.parker@supplyco.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'SupplyCo',
                'phone' => '+1-555-1801',
                'address' => '601 Supply Blvd, Dallas, TX',
                'profile_photo' => 'images/profile/supplier.jpeg',
                'supporting_documents' => json_encode(['owen_parker_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Megan Lewis',
                'email' => 'megan.lewis@retailmart.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'RetailMart',
                'phone' => '+1-555-1901',
                'address' => '701 Retail Ave, Miami, FL',
                'profile_photo' => 'images/profile/retailer.jpeg',
                'supporting_documents' => json_encode(['megan_lewis_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
            [
                'name' => 'Evan Mitchell',
                'email' => 'evan.mitchell@analytica.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Analytica Insights',
                'phone' => '+1-555-2001',
                'address' => '801 Data Lane, Boston, MA',
                'profile_photo' => 'images/profile/analyst.jpeg',
                'supporting_documents' => json_encode(['evan_mitchell_doc1.pdf']),
                'auto_visit_scheduled' => null
            ],
        ];

        // Ensure all users have created_at and updated_at
        foreach ($users as &$user) {
            if (!isset($user['created_at'])) {
                $user['created_at'] = now();
            }
            if (!isset($user['updated_at'])) {
                $user['updated_at'] = now();
            }
            // Only vendors keep their supporting_documents, others get an empty array
            if (!isset($user['role']) || $user['role'] !== 'vendor') {
                $user['supporting_documents'] = json_encode([]);
            }
        }
        unset($user);

        $users = array_map(function($user) {
            return [
                'name' => $user['name'],
                'email' => $user['email'],
                'email_verified_at' => null,
                'password' => $user['password'],
                'role' => $user['role'],
                'status' => $user['status'],
                'company' => $user['company'],
                'phone' => $user['phone'],
                'address' => $user['address'],
                'profile_photo' => $user['profile_photo'],
                'supporting_documents' => $user['supporting_documents'],
                'auto_visit_scheduled' => $user['auto_visit_scheduled'],
                'segment' => null,
                'remember_token' => null,
                'created_at' => $user['created_at'],
                'updated_at' => $user['updated_at'],
            ];
        }, $users);

        DB::table('users')->insert($users);

        // Insert into vendors table for all approved vendors
        $approvedVendors = DB::table('users')->where('role', 'vendor')->where('status', 'approved')->get();
        foreach ($approvedVendors as $user) {
            DB::table('vendors')->insert([
                'user_id' => $user->id,
                'name' => $user->name,
                'email' => $user->email,
                'phone' => $user->phone,
                'password' => $user->password,
                'company' => $user->company,
                'address' => $user->address,
                'profile_picture' => $user->profile_photo,
                'supporting_documents' => $user->supporting_documents,
                'vendor_license' => null,
                'product_categories' => null,
                'service_areas' => null,
                'contract_terms' => null,
                'segment' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        // Attach sample documents to pending users
        $pendingUsers = DB::table('users')->where('status', 'pending')->get();
        $userDocs = [
            // Natalie Simmons (vendor, should pass)
            'natalie.simmons@vendortech.com' => [
                ['file_path' => 'natalie_simmons_financial_statement_2023.pdf', 'document_type' => 'financials'],
                ['file_path' => 'natalie_simmons_iso_certificate.docx', 'document_type' => 'compliance'],
                ['file_path' => 'natalie_simmons_business_license.jpeg', 'document_type' => 'license'],
            ],
            // Derek Foster (vendor, should fail)
            'derek.foster@vendormax.com' => [
                ['file_path' => 'derek_foster_financial_statement_2023.pdf', 'document_type' => 'financials'],
                ['file_path' => 'derek_foster_iso_27001_certificate.jpg', 'document_type' => 'compliance'],
                ['file_path' => 'derek_foster_business_license.docx', 'document_type' => 'license'],
            ],
            // Owen Parker (supplier)
            'owen.parker@supplyco.com' => [
                ['file_path' => 'owen_parker_supplier_registration.pdf', 'document_type' => 'registration'],
                ['file_path' => 'owen_parker_trade_references.jpeg', 'document_type' => 'references'],
                ['file_path' => 'owen_parker_logistics_capabilities.docx', 'document_type' => 'logistics'],
            ],
            // Megan Lewis (retailer)
            'megan.lewis@retailmart.com' => [
                ['file_path' => 'megan_lewis_retail_operating_license.pdf', 'document_type' => 'license'],
                ['file_path' => 'megan_lewis_store_network_overview.docx', 'document_type' => 'overview'],
                ['file_path' => 'megan_lewis_customer_service_policy.png', 'document_type' => 'policy'],
            ],
            // Evan Mitchell (analyst)
            'evan.mitchell@analytica.com' => [
                ['file_path' => 'evan_mitchell_cv.pdf', 'document_type' => 'cv'],
                ['file_path' => 'evan_mitchell_professional_certifications.jpeg', 'document_type' => 'certifications'],
                ['file_path' => 'evan_mitchell_sample_report_excerpt.docx', 'document_type' => 'report'],
            ],
        ];
        foreach ($pendingUsers as $user) {
            if ($user->role === 'vendor' && isset($userDocs[$user->email])) {
                foreach ($userDocs[$user->email] as $doc) {
                    \App\Models\UserDocument::create([
                        'user_id' => $user->id,
                        'file_path' => $doc['file_path'],
                        'document_type' => $doc['document_type'],
                    ]);
                }
            }
        }
    }
} 