<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class ApprovedAndPendingUsersSeeder extends Seeder
{
    public function run()
    {
        $users = [
            // Vendors (examples from user)
            [
                'name' => 'Jennifer Lee',
                'email' => 'jennifer.lee@autoparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'Auto Parts Plus',
                'phone' => '+1-555-0301',
                'address' => '147 Parts Plaza, Dallas, TX',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['jennifer_lee_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Carlos Martinez',
                'email' => 'carlos.martinez@speedparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'Speed Parts International',
                'phone' => '+1-555-0302',
                'address' => '258 Speed Way, Miami, FL',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['carlos_martinez_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Amanda Foster',
                'email' => 'amanda.foster@premiumparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'approved',
                'company' => 'Premium Parts Co',
                'phone' => '+1-555-0303',
                'address' => '369 Premium Drive, Seattle, WA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['amanda_foster_doc1.pdf']),
                'auto_visit_scheduled' => true,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Sofia Rossi',
                'email' => 'sofia.rossi@autotrade.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Auto Trade SRL',
                'phone' => '+39-555-0304',
                'address' => '444 Trade Rd, Rome, Italy',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['sofia_rossi_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Lucas Müller',
                'email' => 'lucas.muller@partsmarket.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Parts Market GmbH',
                'phone' => '+49-555-0305',
                'address' => '555 Market St, Berlin, Germany',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['lucas_muller_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Marta Nowak',
                'email' => 'marta.nowak@autohandel.pl',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Auto Handel',
                'phone' => '+48-555-0306',
                'address' => '808 Warszawska, Warsaw, Poland',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['marta_nowak_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Samuel Johnson',
                'email' => 'samuel.johnson@carzone.co.uk',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'CarZone UK',
                'phone' => '+44-555-0307',
                'address' => '909 High St, London, UK',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['samuel_johnson_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@autotech.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'AutoTech Manufacturing',
                'phone' => '+1-555-0101',
                'address' => '123 Manufacturing Blvd, Detroit, MI',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['sarah_johnson_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'michael.chen@precisionauto.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Precision Auto Works',
                'phone' => '+1-555-0102',
                'address' => '456 Industrial Park, Chicago, IL',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['michael_chen_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Emily Rodriguez',
                'email' => 'emily.rodriguez@qualitycars.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Quality Cars Inc',
                'phone' => '+1-555-0103',
                'address' => '789 Production Lane, Los Angeles, CA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['emily_rodriguez_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Priya Patel',
                'email' => 'priya.patel@futureauto.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Future Auto Ltd',
                'phone' => '+1-555-0104',
                'address' => '101 Innovation Dr, San Jose, CA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['priya_patel_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Liam O\'Connor',
                'email' => 'liam.oconnor@greenmotors.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'approved',
                'company' => 'Green Motors',
                'phone' => '+1-555-0105',
                'address' => '202 Eco Lane, Portland, OR',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['liam_oconnor_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'David Thompson',
                'email' => 'david.thompson@steelparts.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'Steel Parts Supply',
                'phone' => '+1-555-0201',
                'address' => '321 Steel Street, Pittsburgh, PA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['david_thompson_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Lisa Wang',
                'email' => 'lisa.wang@electronicsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'Electronic Supply Co',
                'phone' => '+1-555-0202',
                'address' => '654 Circuit Road, San Jose, CA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['lisa_wang_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Robert Kim',
                'email' => 'robert.kim@glassworks.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'Glass Works Ltd',
                'phone' => '+1-555-0203',
                'address' => '987 Glass Avenue, Toledo, OH',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['robert_kim_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Olga Ivanova',
                'email' => 'olga.ivanova@steelplus.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'Steel Plus',
                'phone' => '+1-555-0204',
                'address' => '222 Steel Ave, Cleveland, OH',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['olga_ivanova_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@rawsupplies.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'approved',
                'company' => 'Raw Supplies Inc',
                'phone' => '+1-555-0205',
                'address' => '333 Raw St, Houston, TX',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['ahmed_hassan_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'James Wilson',
                'email' => 'james.wilson@autosales.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'Auto Sales Network',
                'phone' => '+1-555-0401',
                'address' => '741 Sales Street, Phoenix, AZ',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['james_wilson_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Maria Garcia',
                'email' => 'maria.garcia@cardealers.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'Car Dealers United',
                'phone' => '+1-555-0402',
                'address' => '852 Dealer Road, Denver, CO',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['maria_garcia_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Thomas Brown',
                'email' => 'thomas.brown@autoshowroom.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'Auto Showroom Elite',
                'phone' => '+1-555-0403',
                'address' => '963 Showroom Blvd, Las Vegas, NV',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['thomas_brown_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Hiro Tanaka',
                'email' => 'hiro.tanaka@carhub.jp',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'Car Hub Japan',
                'phone' => '+81-555-0404',
                'address' => '666 Sakura St, Tokyo, Japan',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['hiro_tanaka_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Emma Dubois',
                'email' => 'emma.dubois@voiture.fr',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'approved',
                'company' => 'Voiture France',
                'phone' => '+33-555-0405',
                'address' => '777 Champs Elysees, Paris, France',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['emma_dubois_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Rachel Green',
                'email' => 'rachel.green@marketanalytics.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Market Analytics Pro',
                'phone' => '+1-555-0501',
                'address' => '159 Analytics Lane, Boston, MA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['rachel_green_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Kevin Zhang',
                'email' => 'kevin.zhang@datainsights.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Data Insights Corp',
                'phone' => '+1-555-0502',
                'address' => '357 Data Street, Austin, TX',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['kevin_zhang_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Sophie Anderson',
                'email' => 'sophie.anderson@businessintel.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Business Intelligence Ltd',
                'phone' => '+1-555-0503',
                'address' => '753 Intel Drive, Portland, OR',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['sophie_anderson_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Isabella Costa',
                'email' => 'isabella.costa@analytica.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Analytica Ltd',
                'phone' => '+55-555-0504',
                'address' => '888 Data Ave, Sao Paulo, Brazil',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['isabella_costa_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Noah Smith',
                'email' => 'noah.smith@insightful.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'approved',
                'company' => 'Insightful Analytics',
                'phone' => '+44-555-0505',
                'address' => '999 Insight Rd, London, UK',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['noah_smith_doc1.pdf']),
                'auto_visit_scheduled' => null,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            // Pending users (unique, realistic, distributed roles)
            [
                'name' => 'Giulia Bianchi',
                'email' => 'giulia.bianchi@venditauto.it',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'VenditAuto',
                'phone' => '+39-555-0406',
                'address' => '1010 Via Roma, Milan, Italy',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['giulia_bianchi_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Peter Novak',
                'email' => 'peter.novak@autoprodej.cz',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'AutoProdej',
                'phone' => '+420-555-0407',
                'address' => '1111 Hlavni, Prague, Czech Republic',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['peter_novak_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Emily Clark',
                'email' => 'emily.clark@analyticspro.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Analytics Pro',
                'phone' => '+1-555-0506',
                'address' => '1212 Data Blvd, New York, USA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['emily_clark_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Rajesh Kumar',
                'email' => 'rajesh.kumar@insightindia.in',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Insight India',
                'phone' => '+91-555-0507',
                'address' => '1313 Knowledge Park, Bangalore, India',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['rajesh_kumar_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Juan Perez',
                'email' => 'juan.perez@materiales.mx',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Materiales MX',
                'phone' => '+52-555-0206',
                'address' => '606 Avenida Central, Mexico City, Mexico',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['juan_perez_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Fatima Al-Farsi',
                'email' => 'fatima.alfarsi@omansteel.om',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Oman Steel',
                'phone' => '+968-555-0207',
                'address' => '707 Steel Rd, Muscat, Oman',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['fatima_alfarsi_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Chen Wei',
                'email' => 'chen.wei@dragonauto.cn',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Dragon Auto',
                'phone' => '+86-555-0106',
                'address' => '303 Dragon Rd, Shanghai, China',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['chen_wei_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Anna Schmidt',
                'email' => 'anna.schmidt@autowerk.de',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Autowerk GmbH',
                'phone' => '+49-555-0107',
                'address' => '404 Werkstrasse, Munich, Germany',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['anna_schmidt_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Emily Clark',
                'email' => 'emily.clark2@analyticspro.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Analytics Pro',
                'phone' => '+1-555-0508',
                'address' => '1213 Data Blvd, New York, USA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['emily_clark2_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Santiago Lopez',
                'email' => 'santiago.lopez@latinsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Latin Supply',
                'phone' => '+57-555-0208',
                'address' => '2028 Avenida Sur, Bogota, Colombia',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['santiago_lopez_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Linda Müller',
                'email' => 'linda.muller@euroretail.de',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'EuroRetail',
                'phone' => '+49-555-0408',
                'address' => '1408 Hauptstrasse, Berlin, Germany',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['linda_muller_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Omar Farouk',
                'email' => 'omar.farouk@menaauto.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'MENA Auto',
                'phone' => '+20-555-0108',
                'address' => '108 Nile St, Cairo, Egypt',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['omar_farouk_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Svetlana Petrova',
                'email' => 'svetlana.petrova@rusparts.ru',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'RusParts',
                'phone' => '+7-555-0209',
                'address' => '209 Nevsky Prospekt, St. Petersburg, Russia',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['svetlana_petrova_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Amina Diallo',
                'email' => 'amina.diallo@africar.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'AfriCar',
                'phone' => '+221-555-0409',
                'address' => '409 Dakar Ave, Dakar, Senegal',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['amina_diallo_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Lucas Silva',
                'email' => 'lucas.silva@brazparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'BrazParts',
                'phone' => '+55-555-0308',
                'address' => '308 Avenida Paulista, Sao Paulo, Brazil',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['lucas_silva_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Nina Svensson',
                'email' => 'nina.svensson@nordicsupply.se',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Nordic Supply',
                'phone' => '+46-555-0210',
                'address' => '210 Vasagatan, Stockholm, Sweden',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['nina_svensson_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Mohammed Al-Mansour',
                'email' => 'mohammed.almansour@gulfcars.ae',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Gulf Cars',
                'phone' => '+971-555-0109',
                'address' => '109 Sheikh Zayed Rd, Dubai, UAE',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['mohammed_almansour_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Sophie Dubois',
                'email' => 'sophie.dubois@franalyser.fr',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Franalyser',
                'phone' => '+33-555-0510',
                'address' => '510 Rue de Paris, Lyon, France',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['sophie_dubois_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Jacob Evans',
                'email' => 'jacob.evans@ukretail.co.uk',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'UK Retail',
                'phone' => '+44-555-0410',
                'address' => '410 Oxford St, London, UK',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['jacob_evans_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Elena Rossi',
                'email' => 'elena.rossi@italparts.it',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'ItalParts',
                'phone' => '+39-555-0309',
                'address' => '309 Via Milano, Turin, Italy',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['elena_rossi_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Ahmed Said',
                'email' => 'ahmed.said@egyptmfg.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Egypt Manufacturing',
                'phone' => '+20-555-0110',
                'address' => '110 Nile Corniche, Giza, Egypt',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['ahmed_said_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Megan Lee',
                'email' => 'megan.lee@usanalyst.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'US Analyst Group',
                'phone' => '+1-555-0511',
                'address' => '511 Market St, San Francisco, CA',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['megan_lee_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Carlos Gutierrez',
                'email' => 'carlos.gutierrez@latinvendor.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'LatinVendor',
                'phone' => '+52-555-0310',
                'address' => '310 Calle Central, Monterrey, Mexico',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['carlos_gutierrez_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Samantha Brown',
                'email' => 'samantha.brown@canretail.ca',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'CanRetail',
                'phone' => '+1-555-0411',
                'address' => '411 Yonge St, Toronto, Canada',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['samantha_brown_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Yusuf Demir',
                'email' => 'yusuf.demir@turkmanuf.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'TurkManuf',
                'phone' => '+90-555-0111',
                'address' => '1111 Ataturk Bulvari, Ankara, Turkey',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['yusuf_demir_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Helena Novak',
                'email' => 'helena.novak@czanalyst.cz',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'CZ Analyst',
                'phone' => '+420-555-0512',
                'address' => '512 Karlova, Prague, Czech Republic',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['helena_novak_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
            [
                'name' => 'Olga Petrova',
                'email' => 'olga.petrova@rusretail.ru',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'RusRetail',
                'phone' => '+7-555-0412',
                'address' => '412 Nevsky Prospekt, St. Petersburg, Russia',
                'profile_photo' => 'profile.png',
                'supporting_documents' => json_encode(['olga_petrova_doc1.pdf']),
                'auto_visit_scheduled' => false,
                'created_at' => '2025-07-11',
                'updated_at' => '2025-07-11',
            ],
        ];
        $users = array_map(function ($user) {
            if (!isset($user['role'])) return $user;
            switch ($user['role']) {
                case 'manufacturer':
                    $user['profile_photo'] = 'images/profile/manufacturer.jpeg';
                    break;
                case 'supplier':
                    $user['profile_photo'] = 'images/profile/supplier.jpeg';
                    break;
                case 'retailer':
                    $user['profile_photo'] = 'images/profile/retailer.jpeg';
                    break;
                case 'analyst':
                    $user['profile_photo'] = 'images/profile/analyst.jpeg';
                    break;
                case 'customer':
                    $user['profile_photo'] = 'images/profile/customer.jpeg';
                    break;
                case 'vendor':
                    $user['profile_photo'] = 'images/profile/vendor.jpeg';
                    break;
                case 'admin':
                    // Leave as is, admin already updated
                    break;
                default:
                    $user['profile_photo'] = 'images/profile/default.png';
            }
            return $user;
        }, $users);
        try {
            DB::table('users')->insert($users);
        } catch (\Exception $e) {
            // Optionally log or handle error, but do not halt execution
        }

        // Ensure every vendor with auto_visit_scheduled = true has a FacilityVisit
        $vendors = \App\Models\User::where('role', 'vendor')->where('auto_visit_scheduled', true)->get();
        foreach ($vendors as $vendor) {
            $hasVisit = \App\Models\FacilityVisit::where('user_id', $vendor->id)->exists();
            if (!$hasVisit) {
                \App\Models\FacilityVisit::create([
                    'user_id' => $vendor->id,
                    'company_name' => $vendor->company,
                    'contact_person' => $vendor->name,
                    'contact_email' => $vendor->email,
                    'visit_type' => 'Facility Inspection',
                    'purpose' => 'Initial vendor onboarding assessment',
                    'location' => $vendor->address,
                    'visit_date' => now()->addDays(10),
                    'requested_date' => now(),
                    'status' => 'pending',
                ]);
            }
        }
    }
} 