<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class DemoUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $demoUsers = [
            // Manufacturers
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@autotech.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'AutoTech Manufacturing',
                'phone' => '555-0101',
                'address' => '123 Manufacturing Blvd, Detroit, MI',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'michael.chen@precisionauto.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Precision Auto Works',
                'phone' => '555-0102',
                'address' => '456 Industrial Park, Chicago, IL',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Emily Rodriguez',
                'email' => 'emily.rodriguez@qualitycars.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Quality Cars Inc',
                'phone' => '555-0103',
                'address' => '789 Production Lane, Los Angeles, CA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // NEW MANUFACTURER PENDING USERS
            [
                'name' => 'Priya Patel',
                'email' => 'priya.patel@futureauto.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Future Auto Ltd',
                'phone' => '555-0104',
                'address' => '101 Innovation Dr, San Jose, CA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Liam O\'Connor',
                'email' => 'liam.oconnor@greenmotors.com',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Green Motors',
                'phone' => '555-0105',
                'address' => '202 Eco Lane, Portland, OR',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // Suppliers
            [
                'name' => 'David Thompson',
                'email' => 'david.thompson@steelparts.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Steel Parts Supply',
                'phone' => '555-0201',
                'address' => '321 Steel Street, Pittsburgh, PA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Lisa Wang',
                'email' => 'lisa.wang@electronicsupply.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Electronic Supply Co',
                'phone' => '555-0202',
                'address' => '654 Circuit Road, San Jose, CA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Robert Kim',
                'email' => 'robert.kim@glassworks.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Glass Works Ltd',
                'phone' => '555-0203',
                'address' => '987 Glass Avenue, Toledo, OH',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // NEW SUPPLIER PENDING USERS
            [
                'name' => 'Olga Ivanova',
                'email' => 'olga.ivanova@steelplus.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Steel Plus',
                'phone' => '555-0204',
                'address' => '222 Steel Ave, Cleveland, OH',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@rawsupplies.com',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Raw Supplies Inc',
                'phone' => '555-0205',
                'address' => '333 Raw St, Houston, TX',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // Vendors
            [
                'name' => 'Jennifer Lee',
                'email' => 'jennifer.lee@autoparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Auto Parts Plus',
                'phone' => '555-0301',
                'address' => '147 Parts Plaza, Dallas, TX',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Carlos Martinez',
                'email' => 'carlos.martinez@speedparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Speed Parts International',
                'phone' => '555-0302',
                'address' => '258 Speed Way, Miami, FL',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Amanda Foster',
                'email' => 'amanda.foster@premiumparts.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Premium Parts Co',
                'phone' => '555-0303',
                'address' => '369 Premium Drive, Seattle, WA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // NEW VENDOR PENDING USERS
            [
                'name' => 'Sofia Rossi',
                'email' => 'sofia.rossi@autotrade.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Auto Trade SRL',
                'phone' => '555-0304',
                'address' => '444 Trade Rd, Rome, Italy',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Lucas Müller',
                'email' => 'lucas.muller@partsmarket.com',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Parts Market GmbH',
                'phone' => '555-0305',
                'address' => '555 Market St, Berlin, Germany',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // Retailers
            [
                'name' => 'James Wilson',
                'email' => 'james.wilson@autosales.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'Auto Sales Network',
                'phone' => '555-0401',
                'address' => '741 Sales Street, Phoenix, AZ',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Maria Garcia',
                'email' => 'maria.garcia@cardealers.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'Car Dealers United',
                'phone' => '555-0402',
                'address' => '852 Dealer Road, Denver, CO',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Thomas Brown',
                'email' => 'thomas.brown@autoshowroom.com',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'Auto Showroom Elite',
                'phone' => '555-0403',
                'address' => '963 Showroom Blvd, Las Vegas, NV',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // NEW RETAILER PENDING USERS
            [
                'name' => 'Hiro Tanaka',
                'email' => 'hiro.tanaka@carhub.jp',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'Car Hub Japan',
                'phone' => '555-0404',
                'address' => '666 Sakura St, Tokyo, Japan',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Emma Dubois',
                'email' => 'emma.dubois@voiture.fr',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'Voiture France',
                'phone' => '555-0405',
                'address' => '777 Champs Elysees, Paris, France',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // Analysts
            [
                'name' => 'Rachel Green',
                'email' => 'rachel.green@marketanalytics.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Market Analytics Pro',
                'phone' => '555-0501',
                'address' => '159 Analytics Lane, Boston, MA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Kevin Zhang',
                'email' => 'kevin.zhang@datainsights.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Data Insights Corp',
                'phone' => '555-0502',
                'address' => '357 Data Street, Austin, TX',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Sophie Anderson',
                'email' => 'sophie.anderson@businessintel.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Business Intelligence Ltd',
                'phone' => '555-0503',
                'address' => '753 Intel Drive, Portland, OR',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // NEW ANALYST PENDING USERS
            [
                'name' => 'Isabella Costa',
                'email' => 'isabella.costa@analytica.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Analytica Ltd',
                'phone' => '555-0504',
                'address' => '888 Data Ave, Sao Paulo, Brazil',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Noah Smith',
                'email' => 'noah.smith@insightful.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Insightful Analytics',
                'phone' => '555-0505',
                'address' => '999 Insight Rd, London, UK',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // EVEN MORE MANUFACTURER PENDING USERS
            [
                'name' => 'Chen Wei',
                'email' => 'chen.wei@dragonauto.cn',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Dragon Auto',
                'phone' => '555-0106',
                'address' => '303 Dragon Rd, Shanghai, China',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Anna Schmidt',
                'email' => 'anna.schmidt@autowerk.de',
                'password' => Hash::make('password'),
                'role' => 'manufacturer',
                'status' => 'pending',
                'company' => 'Autowerk GmbH',
                'phone' => '555-0107',
                'address' => '404 Werkstrasse, Munich, Germany',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // EVEN MORE SUPPLIER PENDING USERS
            [
                'name' => 'Juan Perez',
                'email' => 'juan.perez@materiales.mx',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Materiales MX',
                'phone' => '555-0206',
                'address' => '606 Avenida Central, Mexico City, Mexico',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Fatima Al-Farsi',
                'email' => 'fatima.alfarsi@omansteel.om',
                'password' => Hash::make('password'),
                'role' => 'supplier',
                'status' => 'pending',
                'company' => 'Oman Steel',
                'phone' => '555-0207',
                'address' => '707 Steel Rd, Muscat, Oman',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // EVEN MORE VENDOR PENDING USERS
            [
                'name' => 'Marta Nowak',
                'email' => 'marta.nowak@autohandel.pl',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'Auto Handel',
                'phone' => '555-0306',
                'address' => '808 Warszawska, Warsaw, Poland',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Samuel Johnson',
                'email' => 'samuel.johnson@carzone.co.uk',
                'password' => Hash::make('password'),
                'role' => 'vendor',
                'status' => 'pending',
                'company' => 'CarZone UK',
                'phone' => '555-0307',
                'address' => '909 High St, London, UK',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // EVEN MORE RETAILER PENDING USERS
            [
                'name' => 'Giulia Bianchi',
                'email' => 'giulia.bianchi@venditauto.it',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'VenditAuto',
                'phone' => '555-0406',
                'address' => '1010 Via Roma, Milan, Italy',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Peter Novak',
                'email' => 'peter.novak@autoprodej.cz',
                'password' => Hash::make('password'),
                'role' => 'retailer',
                'status' => 'pending',
                'company' => 'AutoProdej',
                'phone' => '555-0407',
                'address' => '1111 Hlavni, Prague, Czech Republic',
                'profile_photo' => 'images/profile.jpeg',
            ],
            // EVEN MORE ANALYST PENDING USERS
            [
                'name' => 'Emily Clark',
                'email' => 'emily.clark@analyticspro.com',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Analytics Pro',
                'phone' => '555-0506',
                'address' => '1212 Data Blvd, New York, USA',
                'profile_photo' => 'images/profile.jpeg',
            ],
            [
                'name' => 'Rajesh Kumar',
                'email' => 'rajesh.kumar@insightindia.in',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'status' => 'pending',
                'company' => 'Insight India',
                'phone' => '555-0507',
                'address' => '1313 Knowledge Park, Bangalore, India',
                'profile_photo' => 'images/profile.jpeg',
            ],
        ];

        foreach ($demoUsers as $userData) {
            User::firstOrCreate(
                ['email' => $userData['email']],
                $userData
            );
        }
    }
} 