<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class VendorSeeder extends Seeder
{
    public function run()
    {
        DB::table('vendors')->truncate();
        $vendors = [
            [
                'user_id' => 2,
                'name' => 'Ava Carter',
                'email' => 'ava.carter@vendortech.com',
                'password' => Hash::make('password'),
                'company' => 'VendorTech Solutions',
                'phone' => '+1-555-1101',
                'address' => '101 Vendor Lane, New York, NY',
                'supporting_documents' => json_encode(['ava_carter_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'name' => 'Benjamin Lee',
                'email' => 'benjamin.lee@autovend.com',
                'password' => Hash::make('password'),
                'company' => 'AutoVend Inc.',
                'phone' => '+1-555-1102',
                'address' => '202 Market St, Los Angeles, CA',
                'supporting_documents' => json_encode(['benjamin_lee_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'name' => 'Chloe Kim',
                'email' => 'chloe.kim@partsplus.com',
                'password' => Hash::make('password'),
                'company' => 'PartsPlus',
                'phone' => '+1-555-1103',
                'address' => '303 Commerce Ave, Chicago, IL',
                'supporting_documents' => json_encode(['chloe_kim_doc1.pdf']),
                'segment' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'name' => 'David Patel',
                'email' => 'david.patel@vendormax.com',
                'password' => Hash::make('password'),
                'company' => 'VendorMax',
                'phone' => '+1-555-1104',
                'address' => '404 Vendor Blvd, Dallas, TX',
                'supporting_documents' => json_encode(['david_patel_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'name' => 'Ella Zhang',
                'email' => 'ella.zhang@autopartspro.com',
                'password' => Hash::make('password'),
                'company' => 'AutoParts Pro',
                'phone' => '+1-555-1105',
                'address' => '505 Parts Ave, San Francisco, CA',
                'supporting_documents' => json_encode(['ella_zhang_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'name' => 'Frank Müller',
                'email' => 'frank.muller@vendorexpress.com',
                'password' => Hash::make('password'),
                'company' => 'VendorExpress',
                'phone' => '+1-555-1106',
                'address' => '606 Express Rd, Miami, FL',
                'supporting_documents' => json_encode(['frank_muller_doc1.pdf']),
                'segment' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'name' => 'Grace Park',
                'email' => 'grace.park@vendornet.com',
                'password' => Hash::make('password'),
                'company' => 'VendorNet',
                'phone' => '+1-555-1107',
                'address' => '707 Network St, Seattle, WA',
                'supporting_documents' => json_encode(['grace_park_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'name' => 'Henry Kim',
                'email' => 'henry.kim@vendorglobal.com',
                'password' => Hash::make('password'),
                'company' => 'VendorGlobal',
                'phone' => '+1-555-1108',
                'address' => '808 Global Ave, Boston, MA',
                'supporting_documents' => json_encode(['henry_kim_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 10,
                'name' => 'Isabella Rossi',
                'email' => 'isabella.rossi@vendormarket.com',
                'password' => Hash::make('password'),
                'company' => 'VendorMarket',
                'phone' => '+1-555-1109',
                'address' => '909 Market St, Chicago, IL',
                'supporting_documents' => json_encode(['isabella_rossi_doc1.pdf']),
                'segment' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 11,
                'name' => 'Jack Wilson',
                'email' => 'jack.wilson@vendordirect.com',
                'password' => Hash::make('password'),
                'company' => 'VendorDirect',
                'phone' => '+1-555-1110',
                'address' => '1010 Direct Dr, Austin, TX',
                'supporting_documents' => json_encode(['jack_wilson_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 12,
                'name' => 'Katherine Lee',
                'email' => 'katherine.lee@vendornow.com',
                'password' => Hash::make('password'),
                'company' => 'VendorNow',
                'phone' => '+1-555-1111',
                'address' => '1111 Now St, Denver, CO',
                'supporting_documents' => json_encode(['katherine_lee_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 13,
                'name' => 'Liam Brown',
                'email' => 'liam.brown@vendorteam.com',
                'password' => Hash::make('password'),
                'company' => 'VendorTeam',
                'phone' => '+1-555-1112',
                'address' => '1212 Team Ave, San Diego, CA',
                'supporting_documents' => json_encode(['liam_brown_doc1.pdf']),
                'segment' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 14,
                'name' => 'Mia Garcia',
                'email' => 'mia.garcia@vendornetwork.com',
                'password' => Hash::make('password'),
                'company' => 'VendorNetwork',
                'phone' => '+1-555-1113',
                'address' => '1313 Network Blvd, Orlando, FL',
                'supporting_documents' => json_encode(['mia_garcia_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 15,
                'name' => 'Noah Smith',
                'email' => 'noah.smith@vendorgroup.com',
                'password' => Hash::make('password'),
                'company' => 'VendorGroup',
                'phone' => '+1-555-1114',
                'address' => '1414 Group St, Atlanta, GA',
                'supporting_documents' => json_encode(['noah_smith_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 16,
                'name' => 'Olivia Davis',
                'email' => 'olivia.davis@vendormarket.com',
                'password' => Hash::make('password'),
                'company' => 'VendorMarket',
                'phone' => '+1-555-1115',
                'address' => '1515 Market Ave, Charlotte, NC',
                'supporting_documents' => json_encode(['olivia_davis_doc1.pdf']),
                'segment' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 17,
                'name' => 'Paul Walker',
                'email' => 'paul.walker@vendorlink.com',
                'password' => Hash::make('password'),
                'company' => 'VendorLink',
                'phone' => '+1-555-1116',
                'address' => '1616 Link St, Portland, OR',
                'supporting_documents' => json_encode(['paul_walker_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 18,
                'name' => 'Quinn Harris',
                'email' => 'quinn.harris@vendornet.com',
                'password' => Hash::make('password'),
                'company' => 'VendorNet',
                'phone' => '+1-555-1117',
                'address' => '1717 Net Ave, Minneapolis, MN',
                'supporting_documents' => json_encode(['quinn_harris_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'name' => 'Ryan Clark',
                'email' => 'ryan.clark@vendorconnect.com',
                'password' => Hash::make('password'),
                'company' => 'VendorConnect',
                'phone' => '+1-555-1118',
                'address' => '1818 Connect Blvd, Salt Lake City, UT',
                'supporting_documents' => json_encode(['ryan_clark_doc1.pdf']),
                'segment' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 20,
                'name' => 'Sophia Martinez',
                'email' => 'sophia.martinez@vendorplus.com',
                'password' => Hash::make('password'),
                'company' => 'VendorPlus',
                'phone' => '+1-555-1119',
                'address' => '1919 Plus St, San Antonio, TX',
                'supporting_documents' => json_encode(['sophia_martinez_doc1.pdf']),
                'segment' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'name' => 'Tyler Nguyen',
                'email' => 'tyler.nguyen@vendortech.com',
                'password' => Hash::make('password'),
                'company' => 'VendorTech',
                'phone' => '+1-555-1120',
                'address' => '2020 Tech Ave, San Jose, CA',
                'supporting_documents' => json_encode(['tyler_nguyen_doc1.pdf']),
                'segment' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('vendors')->insert($vendors);
    }
} 